### ISSUE TITLE
Enabling mobcore makes wildlife mobs disfunction

### ISSUE THREAD

**Issue by Adnan1091** [ElCeejo/mob_core#1]
Enabling this causes wildlife mobs can't be able to climb over blocks.

**Comment by ElCeejo** [comment]
Interesting, this mod doesn't overwrite anything in mobkit so it shouldn't cause any issues with mods that only use mobkit functions. Are you using Gundul's fork or Termos' fork?

**Comment by Adnan1091** [comment]
Gundul's fork. Also this is not the first,volcano mod by facedeer also effected wildlife mod.It was wildlife's problem i suppose because wildlife's file was changed to fix this issue.

**Comment by Adnan1091** [comment]
It seems like only deer in wildlife mod is effected.Petz mod by runs is also effected too.

**Comment by MisterE123** [comment]
Umm, I get this too... Deer cant climb blocks and get stuck. I tried setting stepheight to 1, but that did not fix 

I guess a fix would be to port to mob_core

**Comment by ElCeejo** [comment]
Fixed.
