### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ghost** [ElCeejo/mob_core#7]
Minetest Version: 5.4.1

Mob_core update at commit: 9481b22f8564e13963db1d59487233d5a5373557

Crash:
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '??' in callback luaentity_Step(): /home/minetest/minetest/bin/../mods/mob_core/hq_lq.lua:177: attempt to index a nil value
ERROR[Main]: stack traceback:
ERROR[Main]: 	/home/minetest/minetest/bin/../mods/mob_core/hq_lq.lua:177: in function 'sensor_floor'
ERROR[Main]: 	/home/minetest/minetest/bin/../mods/mob_core/hq_lq.lua:428: in function 'func'
ERROR[Main]: 	/home/minetest/minetest/bin/../mods/mobkit/init.lua:621: in function 'execute_queues'
ERROR[Main]: 	/home/minetest/minetest/bin/../mods/mobkit/init.lua:848: in function 'stepfunc'
ERROR[Main]: 	/home/minetest/minetest/bin/../mods/mob_core/api.lua:1147: in function 'on_step'
ERROR[Main]: 	/home/minetest/minetest/bin/../mods/draconis/api/api.lua:978: in function </home/minetest/minetest/bin/../mods/draconis/api/api.lua:977>

**Comment by ElCeejo** [comment]
Fixed as of the latest commit.

**Comment by ghost** [comment]
thanks
