### ISSUE TITLE
Crashing if draconis mob near

### ISSUE THREAD

**Issue by Ygarr** [ElCeejo/mob_core#9]
Got: 
![errrr2021-05-27_07-09](https://user-images.githubusercontent.com/14309871/119764850-d7e16700-beba-11eb-8845-4d159a79d353.png)

![errrr2021-05-27_07-10](https://user-images.githubusercontent.com/14309871/119764875-ddd74800-beba-11eb-93b9-08745cf2022e.png)

![errrr3__2021-05-27_07-11](https://user-images.githubusercontent.com/14309871/119764885-e3cd2900-beba-11eb-959f-c7edf8d18a7e.png)

**Comment by ElCeejo** [comment]
Grab the latest commit and check if this still occurs.

**Comment by ElCeejo** [comment]
Can't recreate this myself. Closing.
